function donneeslang1 = myimportfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DONNEESLANG1 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a string array.
%
%  DONNEESLANG1 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DONNEESLANG1 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  donneeslang1 = importfile("C:\work\PASS\PISearch\donnees_lang.xlsx", "Sheet1", [2, 10]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 24-Feb-2021 16:59:05

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 10];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Id", "UK", "IT", "FR"];
opts.VariableTypes = ["string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Id", "UK", "IT", "FR"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Id", "UK", "IT", "FR"], "EmptyFieldRule", "auto");

% Import the data
donneeslang1 = readmatrix(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readmatrix(workbookFile, opts, "UseExcel", false);
    donneeslang1 = [donneeslang1; tb]; %#ok<AGROW>
end

end